### ISSUE TITLE
SQL error on route:list

### ISSUE THREAD

**Issue by unarmedwombat** [inFureal/artisan-gui#10]
Get the following MySQL error on running route:list with no options selected:
SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'payload' at row 1 (SQL: update `sessions` set `payload` = YTo2OntzOjY6Il90b2tlbiI7czo0MDoidEM0V1BJZ0pUMm5OeFNZSnY4a21YbkEzaUVXSG5vaEhwbks0eXJQZyI7czo5OiJfcHJldmlvdXMiO2.... (data exceeds 32k characters)
Laravel 8.12 / MySQL 5.7
Runs ok with compact option selected

**Comment by inFureal** [comment]
That is not problem of this package. Probably this error from database, because Artisan GUI not touching DB at all.
