### ISSUE TITLE
Version 1.4.1 doesn't work with laravel jetsream livewire stack

### ISSUE THREAD

**Issue by dukenst2006** [inFureal/artisan-gui#11]
Hi, 
Thanks for this great package, i discovered the latest version 1.4.1 is incompatible with laravel Jetstream livewire stack, I used jetstream and this package, it works great with version 1.3, but after update all packages, i got error 'Livewire\Exceptions\ComponentNotFoundException' Unable to find component: [profile.update-profile-information-form], the same message for all Laravel Jetstream livewire components.
It's took me 2 days to debug and finally found this issue related to this package and specially version 1.4.1, after came back to version 1.3 o this package my app works fine again.

**Comment by inFureal** [comment]
Can you please write Laravel, PHP and Livewire versions. 
And if possible give part of `.blade.php` where error is appears.

I think it's error of template namespacing. If you can not write template part - are you using `<livewire:some>` or `@livewire('some')`?

**Comment by inFureal** [comment]
I tested myself with this parameters:
- PHP 7.4
- `laravel/framework`@8.17.2
- `laravel/jetsteam`@1.6.3
- `livewire/livewire`@2.3.5
- `infureal/artisan-gui`@1.4.1

Works pretty fine.

**Comment by NanoCellWebDesign** [comment]
I have same issue, when I removed artisan GUI Jetstream worked fine again.

https://github.com/livewire/livewire/discussions/1764#discussioncomment-184155

**Comment by inFureal** [comment]
recently released version 2.0@beta where was removed blade component regsiter.
All of stuff moved to Vue, except one .blade.php template (not component). You can try to upgrade and test again

**Comment by inFureal** [comment]
@dukenst2006 @NanoCellWebDesign 
For now I close this issue. If have new one open it again
