### ISSUE TITLE
Limit access to specific users

### ISSUE THREAD

**Issue by NanoCellWebDesign** [inFureal/artisan-gui#12]
Maybe it would be possible that if, when in production, it would only allow certain users to access the routes?

this would make it really useful for people on shared hosting with no access to SSH

**Comment by inFureal** [comment]
You can do it through middleware.
```php
\\ ...
if (!$request->user()->isAdmin())
    abort(403);
\\ ....
```

**Comment by inFureal** [comment]
I have a plan to implement [this issue](https://github.com/inFureal/artisan-gui/issues/9). But right now it's possible only in middleware
