### ISSUE TITLE
Incorrect display of tables in command

### ISSUE THREAD

**Issue by Catzilla** [inFureal/artisan-gui#18]
Tables are broken due to incorrect handling of spaces

### Environment

- PHP 8.0.3
- Laravel 8.31.0
- Artisan GUI 2.0.0@beta

### Screenshot

![image](https://user-images.githubusercontent.com/11861208/110361686-07fe3400-8049-11eb-8f9d-5b960aa6e698.png)

### Code to reproduce

```php
<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;

class VarDump extends Command
{
    protected $signature = 'var:dump';

    protected $description = 'Test command';

    public function handle(): void
    {
        $this->table([], [
            ['User email', 'user@localhost'],
            ['User ID', 1],
            ['Some another row 1', 'xxxxx'],
            ['Some another row 2', 'yyyyyyyyyyy'],
        ]);
    }
}
```

### Solution

Display command output with `white-space: pre;` (Pull request proposed)

**Comment by Oxicode** [comment]
+1

**Comment by olPdy** [comment]
> Таблицы сломаны из-за неправильной обработки пробелов
> 
> ### Окружающая среда
> * PHP 8.0.3
> * Ларавель 8.31.0
> * Графический интерфейс мастера 2.0.0@beta
> 
> ### Скриншот
> ![изображение](https://user-images.githubusercontent.com/11861208/110361686-07fe3400-8049-11eb-8f9d-5b960aa6e698.png)
> 
> ### Код для воспроизведения
> ```
> <?php
> 
> namespace App\Console\Commands;
> 
> use Illuminate\Console\Command;
> 
> class VarDump extends Command
> {
>     protected $signature = 'var:dump';
> 
>     protected $description = 'Test command';
> 
>     public function handle(): void
>     {
>         $this->table([], [
>             ['User email', 'user@localhost'],
>             ['User ID', 1],
>             ['Some another row 1', 'xxxxx'],
>             ['Some another row 2', 'yyyyyyyyyyy'],
>         ]);
>     }
> }
> ```
> 
> ### Решение
> Отобразить вывод команды с помощью `white-space: pre;`(предложен запрос на извлечение)

+
