### ISSUE TITLE
Undefined constant STDIN when command is interactive 

### ISSUE THREAD

**Issue by jeremy379** [infureal/artisan-gui#32]
Hello

I encounter an issue (beta v2) while trying command with interactive question (using $this->ask() or variant of it). Do you plan to support this in the next version? 

This code will produce an error 

```
exception: "Error"
file: "/home/vagrant/code/platform/vendor/symfony/console/Helper/QuestionHelper.php"
line: 113
message: "Undefined constant \"STDIN\""
```

Code example to reproduce the issue :
```
class MyTestCommand extends Command
{
	protected $signature = 'test';
	protected $description = 'Test command';

	public function handle()
	{

		$this->ask('hello ? ');

		return 0;
	}
}
```

**Comment by infureal** [comment]
STDIN (standart output) is disabled for php-cgi. It works only in cli. So you cannot realtime promt user for answer.
