### ISSUE TITLE
Not suitable with Laravel 9.x

### ISSUE THREAD

**Issue by neondev27** [inFureal/artisan-gui#39]
I tried install it but not eligable with Laravel 9.x

**Comment by infureal** [comment]
Hello. What exactly went wrong with installation?

**Comment by neondev27** [comment]
I just typed beta installation command but its says it:
 Problem 1
    - Root composer.json requires infureal/artisan-gui 2.0.0@beta -> satisfiable by infureal/artisan-gui[2.0.0@beta].
    - infureal/artisan-gui 2.0.0@beta requires laravel/framework ^8.0 -> found laravel/framework[v8.0.0, ..., 8.x-dev] but it conflicts with your root composer.json require (^9.19).

**Comment by infureal** [comment]
try with `--ignore-platform-reqs`

**Comment by neondev27** [comment]
just nevermind, i done it, just used normal install command, thx for solution.
