### ISSUE TITLE
Undefined constant 'STDIN'

### ISSUE THREAD

**Issue by m-rizal-02** [inFureal/artisan-gui#4]
I have a problem running make: controller in laravel 8.0.

Message error: **Undefined constant 'STDIN'**

**Comment by inFureal** [comment]
Seems like you tried to run command that required runtime input.
This is not that I'm expected, because validator not pass you through if you have rqeuired empty fields.

Can you write php version, laravel version, all steps you've done to try it myself?

**Comment by inFureal** [comment]
Try to update this package to 1.4 version
`composer update infureal/artisan-gui`

**Comment by raynirola** [comment]
> Try to update this package to 1.4 version
> `composer update infureal/artisan-gui`

This happened to me when trying to make a nested controller. 

<img width="1235" alt="Screenshot 2020-11-21 at 12 58 19" src="https://user-images.githubusercontent.com/54945029/99870488-5a7e2680-2bf9-11eb-8908-16f9f0351d19.png">
<img width="1235" alt="Screenshot 2020-11-21 at 12 58 08" src="https://user-images.githubusercontent.com/54945029/99870491-5fdb7100-2bf9-11eb-8d24-05f7fc06054c.png">

**Comment by Kamona-WD** [comment]
if you try run this command directly in console
`php artisan make:controller PostCommentController --parent=PostController`
it will prompt to ask you
`App\Models\PostController model does not exist. Do you want to generate it? (yes/no) [yes]:`
While doing so, the Symfony/Console component will use the built-in STDIN PHP constant to capture the input stream. That constant is only available in the CLI environment. so in general we should disable the interactivity

**Comment by inFureal** [comment]
@Kamona-WD has good answer to this. So I think we can close this issue
