### ISSUE TITLE
Exclude self from Maintenance Mode

### ISSUE THREAD

**Issue by jezmck** [inFureal/artisan-gui#6]
This package needs a way to exclude itself from Maintenance Mode (503).

It may be that we simply need some instructions on how to achieve this, such as those at https://statamic.dev/knowledge-base/excluding-the-control-panel-from-maintenance-mode#excluding-urls (editing the CheckForMaintenanceMode middleware).

**Comment by inFureal** [comment]
Yeap, I'll thinking to add some instructions in README.
But any package doesn't have oportunities to change your code in YOUR app
