### ISSUE TITLE
Allow list/run specific commands based on authorization

### ISSUE THREAD

**Issue by Arcesilas** [inFureal/artisan-gui#9]
Hi,

It could be very nice to be able to only display/run commands depending on Gate authorization.

For example, the commands list from config file could be something like:

```php
'commands' => [
    'group-name' => [
        'foo:bar',    // Ok for everyone (who can access artisan gui)
        'can-run-baz' => 'baz'// Only for users with permission 'can-run-baz'
    ]
]
```

It requires to read the list before building the gui panel. Something like:

```php
use Gate;

class GuiController extends Controller {
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;

    function index() {
        $commands = array_filter(config('artisan-gui.commands', []), function ($command, $permission) {
            return is_string($permission) ? Gate::allows($permission) : true;
        },  ARRAY_FILTER_USE_BOTH);
        return view('gui::index', [
            'commands' => array_values($commands)
        ]);
    }
```

This is raw code just to get the idea, a method should retrieve the filtered commands.
Permission should also be checked before runningg the command.

This feature should not introduce any BC. I may provide a PR if you're ok with this.

**Comment by inFureal** [comment]
Great idea but I think this is must be as independent type of config, because of `[refactoring/searching bugs/collecting all in one garbage]`.

Perhaps, it would be somthing like this:
```php
return [
    'premissions' => [
        'foo:bar' => ['can-run-command', 'can-run-foo-bar'],
        'something-else' => 'do-what-you-want'
    ]
];
```

**Comment by inFureal** [comment]
Version 2.0 is here with your idea implemented.
[#7ec78e7](https://github.com/inFureal/artisan-gui/commit/7ec78e73b5a8371ba407da626c97cb55809540ac)
